// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Color.proto

#include "Color.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ColorPackage {
}  // namespace ColorPackage
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Color_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Color_2eproto = nullptr;
const uint32_t TableStruct_Color_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Color_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013Color.proto\022\014ColorPackage*1\n\005Color\022\007\n\003"
  "Red\020\000\022\t\n\005Green\020\003\022\n\n\006Yellow\020\006\022\010\n\004Blue\020\tb\006"
  "proto3"
  ;
static ::_pbi::once_flag descriptor_table_Color_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Color_2eproto = {
    false, false, 86, descriptor_table_protodef_Color_2eproto,
    "Color.proto",
    &descriptor_table_Color_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_Color_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Color_2eproto,
    file_level_service_descriptors_Color_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Color_2eproto_getter() {
  return &descriptor_table_Color_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Color_2eproto(&descriptor_table_Color_2eproto);
namespace ColorPackage {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Color_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Color_2eproto);
  return file_level_enum_descriptors_Color_2eproto[0];
}
bool Color_IsValid(int value) {
  switch (value) {
    case 0:
    case 3:
    case 6:
    case 9:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ColorPackage
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
